name: CI workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Pull changes
        run: git pull --no-rebase --no-tags

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Verify pip cache directory
        run: |
          echo "Checking pip cache directory:"
          mkdir -p ~/.cache/pip
          ls -la ~/.cache/pip

      - name: Cache Python dependencies
        id: cache-pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('./scraper/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./scraper/requirements.txt

      - name: Lint with flake8
        run: |
          flake8 scraper --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 scraper --count --max-complexity=10 --max-line-length=127 --statistics

      - name: Type check with mypy
        run: |
          pip install boto3-stubs
          mypy --install-types --non-interactive scraper

      - name: Format with black
        run: |
          black scraper

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./scraper
          file: ./scraper/Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/car-scraper:latest

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Pull changes
        run: git pull --no-rebase --no-tags

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Verify pip cache directory
        run: |
          echo "Checking pip cache directory:"
          mkdir -p ~/.cache/pip
          ls -la ~/.cache/pip

      - name: Cache Python dependencies
        id: cache-pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('./scraper/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./scraper/requirements.txt

      - name: Test with pytest
        run: |
          pytest --junitxml=test-results.xml --cov=scraper --cov-report=xml

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results.xml

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
